% =========================================================================
% Paper: Towards a Digital Twin for the Quantitative Risk Assessment of
%     Domino Effects in Fuel Storage Facilities
% Repository: https://github.com/ramon-quiza/qra-domino-fuel-storage
% File: Computes the distribution of radiation for each scenario
% -------------------------------------------------------------------------
% (c) 2026, Centre for Advanced and Sustainable Manufacturing Studies
%           University of Matanzas
% =========================================================================
% For each of the 2^5 = 32 possible final fire configurations (each tank
% either burning or intact), this script:
%   1. Counts how many Monte Carlo scenarios (from m01) ended in that
%      configuration
%   2. Computes the thermal radiation field over a grid surrounding the
%      facility, using the point-source model implemented in rad2point
%   3. Plots the tank layout and the iso-radiation contours at selected
%      damage threshold levels, and saves figure and data files
% -------------------------------------------------------------------------
% References:
%   [1] Mudan, K.S. (1984). Thermal radiation hazards from hydrocarbon
%       pool fires. Progress in Energy and Combustion Science, 10(1),
%       59-80. (point-source radiation model, as implemented in
%       rad2point)
%   [2] Raj, P.K. (2008). A review of the criteria for people exposure
%       to radiant heat flux from fires. Journal of Hazardous
%       Materials, 159(1), 61-71. (harm criteria for thermal radiation
%       exposure; ~2 kW/m2 pain threshold, 5 kW/m2 common safety
%       criterion for people)
%   [3] CCPS (2000). Guidelines for Chemical Process Quantitative Risk
%       Analysis, 2nd ed. AIChE, New York. (damage threshold values of
%       thermal radiation: ~12.5 kW/m2 for piloted ignition of wood
%       and plastics, ~37.5 kW/m2 for damage to process equipment and
%       steel storage tanks)
% =========================================================================
clear all;                                       % Clear workspace variables
clc;                                             % Clear command window

% -------------------------------------------------------------------------
% Tank farm layout: position and geometry of each storage tank
% (one column per tank; 5 tanks in total), in the GLOBAL coordinate
% system of the complex (see the layout figure and data tables)
% -------------------------------------------------------------------------
x =   [150.0  220.0  177.0  162.5  217.5];       % X-axis centre position [m]
y =   [150.0  150.0  177.0  240.0  240.0];       % Y-axis centre position [m]
D =   [ 15.0   10.0   10.0   22.0   22.0];       % Diameter [m]
H =   [ 12.0    8.0   10.0   12.0   12.0];       % Height [m]

% -------------------------------------------------------------------------
% Thermophysical properties of the fuel contained in the tanks
% - Tank 1: Light naphtha (n-hexane) [https://www.chemeo.com/cid/14-924-0/n-Hexane]
% - Tanks 2 & 3: Jet fuel (n-decane) [https://www.chemeo.com/cid/44-644-8/Decane]
% - Tanks 4 & 5: Diesel (n-dodecane) [https://www.chemeo.com/cid/34-125-5/Dodecane]
% -------------------------------------------------------------------------
T_b = [ 68.7  174.2  174.2  216.3  216.3];       % Boiling point [oC]
H_c = [ 44.7   47.6   47.6   47.5   47.5].*1e3;  % Heat of combustion [kJ/kg]
H_v = [366.0  361.0  361.0  256.0  256.0];       % Heat of vaporization [kJ/kg]
c_P = [  2.27   2.21   2.21   2.21   2.21];      % Specific heat [kJ/(kg.K)]

% -------------------------------------------------------------------------
% Load the accident scenarios generated by m01_generate_scenarios:
%   id  - ignition step of each tank (0 = intact, 1 = primary, >1 = domino)
%   Q_R - heat released by each tank in each scenario [kW]
%   I_R - radiation intensity received by each tank in each scenario [kW/m2]
% -------------------------------------------------------------------------
load('./data/scenarios.mat');

% -------------------------------------------------------------------------
% Computation grid: (N+1) x (N+1) points covering the facility plus a
% 180 m margin on every side, enough to contain the lowest iso-radiation
% contour of interest and every building and machinery item of the
% complex (in the global frame the grid spans [-30, 400] x [-30, 420] m)
% -------------------------------------------------------------------------
x_min = min(x) - 180;                            % Left boundary of the grid [m]
x_max = max(x) + 180;                            % Right boundary of the grid [m]
y_min = min(y) - 180;                            % Bottom boundary of the grid [m]
y_max = max(y) + 180;                            % Top boundary of the grid [m]
N = 100;                                         % Grid subdivisions per axis
[X, Y] = meshgrid(x_min + [0 : N].*(x_max - x_min)./N, y_min + [0 : N].*(y_max - y_min)./N);

% Characteristic (maximum) heat release of each tank over all the
% scenarios [kW]; since the pool fire model depends only on the tank
% geometry and fuel, this recovers the heat released by each tank
% whenever it burns
Q_max = max(Q_R);

% All 2^5 = 32 possible fire configurations, encoded as binary vectors:
% scens(n, j) = 1 -> tank j is burning in configuration n
scens = dec2bin(0:2^5-1) - '0';

% -------------------------------------------------------------------------
% Radiation field and occurrence count for each fire configuration
% -------------------------------------------------------------------------
for n = 1 : size(scens, 1)
    % Configuration label, e.g. '01001' (tanks 2 and 5 burning)
    S = strrep(num2str(scens(n, :)), ' ', '');

    % Number of Monte Carlo scenarios whose final state matches this
    % configuration exactly (a tank burned if id >= 1; the comparison
    % must hold simultaneously for the 5 tanks)
    C = sum(sum((id >= 1) == scens(n, :), 2) == 5);

    % Radiation intensity [kW/m2] received at every grid point from the
    % burning tanks of this configuration (point-source model [1])
    Z = zeros(size(X));                          % Preallocate the radiation field
    for i = 1 : size(X, 1)
        for j = 1 : size(X, 2)
            Z(i, j) = rad2point(X(i, j), Y(i, j), Q_max.*scens(n, :), x, y, D);
        end
    end

    % ---------------------------------------------------------------------
    % Plot: tank layout and iso-radiation contours
    % ---------------------------------------------------------------------
    fig = figure;
    hold on;
    % Tank outlines (circles of diameter D centred at (x, y))
    theta = linspace(0, 2*pi, 100);
    for t = 1 : length(D)
        x_circ = x(t) + D(t)/2.*cos(theta);
        y_circ = y(t) + D(t)/2.*sin(theta);
        plot(x_circ, y_circ, 'k-');
    end
    % Iso-radiation contours at the damage threshold levels [kW/m2]
    % adopted for the consequence assessment [2, 3]:
    %    2   - pain threshold for exposed people
    %    5   - common safety criterion for people (second-degree burns
    %          within tens of seconds of exposure)
    %   12.5 - piloted ignition of wood and plastics; escalation
    %          threshold commonly adopted for domino effect assessment
    %   37.5 - damage to process equipment and steel storage tanks
    contour(X, Y, Z, [2, 5, 12.5, 37.5]);
    % Figure title: configuration label and number of occurrences
    title([S, ' - ', num2str(C)]);
    axis equal;

    % ---------------------------------------------------------------------
    % Save the figure (.fig and .png) and the data of this configuration:
    %   X, Y - grid coordinates [m]; Z - radiation field [kW/m2]
    %   C    - occurrence count;     S - configuration label
    % ---------------------------------------------------------------------
    saveas(fig, sprintf('./figures/scenarios/scenario_%s.fig', S));
    saveas(fig, sprintf('./figures/scenarios/scenario_%s.png', S));
    save(sprintf('./data/scenarios/scenario_%s.mat', S), 'X', 'Y', 'Z', 'C', 'S');
    close all;

    % Progress report
    fprintf('Computed %d of %d configurations\n', n, size(scens, 1));

end