% =========================================================================
% Paper: Towards a Digital Twin for the Quantitative Risk Assessment of
%     Domino Effects in Fuel Storage Facilities
% Repository: https://github.com/ramon-quiza/qra-domino-fuel-storage
% File: Fits a Gamma distribution to the radiation intensity received
%     at each grid point over all the accident scenarios
% -------------------------------------------------------------------------
% (c) 2026, Centre for Advanced and Sustainable Manufacturing Studies
%           University of Matanzas
% =========================================================================
% At every point of the computation grid, the radiation intensities
% received over all the scenario occurrences (Z_data, from m04) form a
% sample of a non-negative, right-skewed random variable. This script
% fits a two-parameter Gamma distribution to that sample by maximum
% likelihood estimation, producing two maps: A (shape parameter) and
% B (scale parameter). These maps characterise, in probabilistic terms,
% the radiation field of the facility, and are the target data for the
% surrogate (neural network) model trained in m06.
% -------------------------------------------------------------------------
% References:
%   [1] Johnson, N.L., Kotz, S., Balakrishnan, N. (1994). Continuous
%       Univariate Distributions, Vol. 1, 2nd ed. Wiley, New York.
%       (Gamma distribution and its maximum likelihood estimation)
%   [2] Anderson, T.W., Darling, D.A. (1952). Asymptotic theory of
%       certain "goodness of fit" criteria based on stochastic
%       processes. Annals of Mathematical Statistics, 23(2), 193-212.
%       (Anderson-Darling goodness-of-fit test, left available in the
%       code for the validation of the fitted distributions)
% =========================================================================
clear all                                        % Clear workspace variables
clc                                              % Clear command window

% -------------------------------------------------------------------------
% Tank farm layout (X-axis and Y-axis centre positions [m]), needed
% only to rebuild the computation grid used in m02
% -------------------------------------------------------------------------
x =   [150.0  220.0  177.0  162.5  217.5];       % [m] (GLOBAL frame)
y =   [150.0  150.0  177.0  240.0  240.0];       % [m] (GLOBAL frame)

% -------------------------------------------------------------------------
% Computation grid: must be identical to the one defined in m02
% (facility plus a 180 m margin on every side, N+1 points per axis)
% -------------------------------------------------------------------------
x_min = min(x) - 180;                            % Left boundary of the grid [m]
x_max = max(x) + 180;                            % Right boundary of the grid [m]
y_min = min(y) - 180;                            % Bottom boundary of the grid [m]
y_max = max(y) + 180;                            % Top boundary of the grid [m]

N = 100;                                         % Grid subdivisions per axis
[X, Y] = meshgrid(x_min + [0 : N].*(x_max - x_min)./N, y_min + [0 : N].*(y_max - y_min)./N);

% Scenario-wise radiation sample generated by m04:
%   Z_data(n, i, j) - radiation intensity [kW/m2] received at grid
%   point (i, j) in the n-th scenario occurrence
load('./data/z_data.mat');

% -------------------------------------------------------------------------
% Point-wise Gamma fitting by maximum likelihood estimation [1]
% -------------------------------------------------------------------------
for i = 1 : size(Z_data, 2)
    for j = 1 : size(Z_data, 3)
        % Sample of radiation intensities at grid point (i, j) over all
        % the scenario occurrences (note: this reuses -shadows- the
        % variable name x, no longer needed as tank position)
        x = Z_data(:, i, j);
        % Maximum likelihood estimates of the Gamma parameters
        p_hat = mle(x, 'distribution', 'gamma');
        A(i, j) = p_hat(1);                      % Shape parameter [-]
        B(i, j) = p_hat(2);                      % Scale parameter [kW/m2]
        % Optional goodness-of-fit check (Anderson-Darling test [2]);
        % note that the sample takes at most 2^5 - 1 distinct values, so
        % the test must be interpreted with care
        %[h, p] = adtest(x, 'Distribution', 'gamma');
    end
end

% -------------------------------------------------------------------------
% Save the fitted parameter maps:
%   X, Y - grid coordinates [m]
%   A    - Gamma shape parameter at each grid point [-]
%   B    - Gamma scale parameter at each grid point [kW/m2]
% -------------------------------------------------------------------------
save('./data/gamma_data.mat', 'X', 'Y', 'A', 'B');

% -------------------------------------------------------------------------
% Plot: contour maps of the fitted shape (A) and scale (B) parameters
% -------------------------------------------------------------------------
fig = figure;
subplot(1, 2, 1);
contour(X, Y, A);
axis equal;
subplot(1, 2, 2);
contour(X, Y, B);
axis equal;
saveas(fig, './figures/gamma_dists.fig');
saveas(fig, './figures/gamma_dists.png');
