% =========================================================================
% Paper: Towards a Digital Twin for the Quantitative Risk Assessment of
%     Domino Effects in Fuel Storage Facilities
% Repository: https://github.com/ramon-quiza/qra-domino-fuel-storage
% File: Fits the neural network (GRNN) surrogate models of the Gamma
%     parameter maps
% -------------------------------------------------------------------------
% (c) 2026, Centre for Advanced and Sustainable Manufacturing Studies
%           University of Matanzas
% =========================================================================
% This script builds the data-driven core of the digital twin: two
% Generalized Regression Neural Networks (GRNN) [1] that map any
% position (x, y) of the terrain to the shape (A) and scale (B)
% parameters of the Gamma distribution of the radiation intensity
% fitted in m05. Once trained, the networks allow the probabilistic
% radiation field to be evaluated at arbitrary points, without being
% restricted to the computation grid (see m07 and m08).
% Alternative surrogate models explored during development (multilayer
% feedforward networks trained with Levenberg-Marquardt, and fuzzy
% inference systems generated by FCM clustering) are kept commented out
% for reference.
% -------------------------------------------------------------------------
% References:
%   [1] Specht, D.F. (1991). A general regression neural network. IEEE
%       Transactions on Neural Networks, 2(6), 568-576.
%       https://doi.org/10.1109/72.97934 (GRNN architecture; the only
%       hyperparameter is the spread of the radial basis functions)
% =========================================================================
clear all;                                       % Clear workspace variables
clc;                                             % Clear command window

% -------------------------------------------------------------------------
% Load the Gamma parameter maps fitted in m05:
%   X, Y - grid coordinates [m]
%   A    - Gamma shape parameter at each grid point [-]
%   B    - Gamma scale parameter at each grid point [kW/m2]
% -------------------------------------------------------------------------
load('./data/gamma_data.mat');

% Flatten the grids into column vectors (one training sample per row)
x = reshape(X, numel(X), 1);
y = reshape(Y, numel(Y), 1);
a = reshape(A, numel(A), 1);
b = reshape(B, numel(B), 1);

% -------------------------------------------------------------------------
% Alternative surrogate models (kept for reference, not used)
% -------------------------------------------------------------------------
% Multilayer feedforward networks trained with Levenberg-Marquardt:
% net_a = feedforwardnet(25, 'trainlm');
% net_a.trainParam.max_fail = 10000;
% net_a.trainParam.epochs = 1000;
% net_a = train(net_a, [x, y].', a.');
% a_hat = net_a([x, y].').';
%
% net_b = feedforwardnet(81, 'trainlm');
% net_b.trainParam.max_fail = 10000;
% net_b.trainParam.epochs = 1000;
% net_b = train(net_b, [x, y].', b.');
% b_hat = net_b([x, y].').';

% Fuzzy inference systems generated by FCM clustering:
% options = genfisOptions('FCMClustering');
% fis_a = genfis([x, y], a, options);
% a_hat = evalfis(fis_a, [x, y].').';
% fis_b = genfis([x, y], b, options);
% b_hat = evalfis(fis_b, [x, y].').';

% -------------------------------------------------------------------------
% GRNN surrogate models [1]: (x, y) -> A and (x, y) -> B, with a
% spread of 2 m (equivalent Gaussian width sigma = spread/1.1774 =
% 1.70 m, i.e. about half the grid spacing of 4.3-4.5 m), which
% controls the smoothness of the interpolation. Note that the
% goodness-of-fit metrics computed on the training points (see
% regression_metrics.m and Table 6 of the paper) certify the
% reproduction of the fitted maps, not the prediction at unseen points.
% -------------------------------------------------------------------------
net_a = newgrnn([x, y].', a.', 2);
a_hat = net_a([x, y].').';                       % Network response on the training points

net_b = newgrnn([x, y].', b.', 2);
b_hat = net_b([x, y].').';                       % Network response on the training points

% -------------------------------------------------------------------------
% Plot: predicted vs fitted parameters (points on the identity line
% indicate a perfect reproduction of the Gamma parameter maps)
% -------------------------------------------------------------------------
fig = figure;
subplot(1, 2, 1);
plot(a, a_hat, '.');
axis equal;
subplot(1, 2, 2);
plot(b, b_hat, '.');
axis equal;
saveas(fig, './figures/gnn_model.fig');
saveas(fig, './figures/gnn_model.png');

% -------------------------------------------------------------------------
% Save the trained networks for the forecasting scripts (m07, m08)
% -------------------------------------------------------------------------
save('./data/grnn_data.mat', 'net_a', 'net_b');
